Neos:
  Neos:
    modules:
      administration:
        submodules:
          administration:
            label: "Connections Manager"
            description: "Administer all MCP Connections"
            icon: "fa-magic-wand-sparkles"
            controller: 'SJS\Neos\MCP\Controller\Backend\AdministrationModuleController'
            privilegeTarget: "SJS.Neos.MCP:AdministrationModuleController.Base"

      mcp:
        # label: "Neos.Neos:Modules:management.label"
        label: "MCP"
        controller: 'SJS\Neos\MCP\Controller\Backend\BaseMcpModuleController'
        # description: "Neos.Neos:Modules:management.description"
        description: "Things"
        icon: fas fa-briefcase
        mainStylesheet: "Lite"
        submodules:
          connections:
            label: "Connections"
            description: "Manage your MCP connections"
            icon: "fas fa-magic-wand-sparkles"
            controller: 'SJS\Neos\MCP\Controller\Backend\UserConnectionController'
            privilegeTarget: "SJS.Neos.MCP:UserConnectionModule"
