Neos:
  Neos:
    modules:
      administration:
        submodules:
          identityModule:
            label: "Identities"
            description: "MCP identity management"
            icon: "fa-magic-wand-sparkles"
            controller: 'SJS\Neos\MCP\Controller\Backend\IdentityModuleController'
            privilegeTarget: "SJS.Neos.MCP:IdentityModuleController.Base"
