SJS:
  Neos:
    MCP:
      server:
        # configuration for the default server
        mcp:
          capabilities:
            resources:
              listChanged: false
              subscribe: false
          featureSets:
            webPage: \SJS\Neos\MCP\FeatureSet\WebPageFeatureSet
            asset: \SJS\Neos\MCP\FeatureSet\AssetFeatureSet
